### PR TITLE
Restructure the project to allow nimble check to pass

### PR DESCRIPTION
**Pull request by yyoncho**
- This is similar to @zah's https://github.com/status-im/nim-secp256k1/pull/36
- I have tested `nimble check`/`nimble test`/`make test` and they are green. Please, let me know if I have to try something else.

### CODE REVIEW

**Comment by arnetheduck** [comment]
cc @yyoncho  can you bump this in nimbus-eth2 to see that it still compiles / works as expected?

**Comment by yyoncho** [comment]
@arnetheduck see https://github.com/status-im/nim-libbacktrace/pull/27/

**Comment by arnetheduck** [comment]
yes - however, the tests in the library are pretty useless - the important test is whether nimbus-eth2 still compiles and works, because that's where these things actually get stressed properly across platforms

**Comment by yyoncho** [comment]
> yes - however, the tests in the library are pretty useless - the important test is whether nimbus-eth2 still compiles and works, because that's where these things actually get stressed properly across platforms

I did `make` and `make test` in eth2. That is how I found the path issue. I hope that this is enough.

**Comment by arnetheduck** [comment]
> I did make and make test in eth2. That is how I found the path issue

the thing we do when making PR:s like this is a bump pr on nimbus-eth2, like so: https://github.com/status-im/nimbus-eth2/pull/3783 - sometimes, we might do other projects as well, but eth2 is a good litmus test - testing on your own machine is not enough, it needs to work across all platforms etc - usually, the person making a change to a library like this is also best equipped to deal with the fallout (because they know what the change is about)

**Comment by arnetheduck** [comment]
it's a bit messy, but what you do is open a PR for the change on the library, then one on eth2, then when the library change is merged, the one on eth2 typically needs updating (because of the submodule commit hash update).

**Comment by yyoncho** [comment]
@arnetheduck it took some time, but it is green: https://github.com/status-im/nimbus-eth2/pull/3794

**Comment by arnetheduck** [comment]
perfect, thanks!

**Pull request merged**
